# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
