# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0002_auto_20170424_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Rating Data',
                'verbose_name_plural': 'Rating Data',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['movie_id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URLDispatcher.Movie'),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URLDispatcher.User'),
        ),
    ]
