# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0007_auto_20170501_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='link',
            new_name='links',
        ),
    ]
