# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0010_auto_20170501_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
