# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0012_movie_movie_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['movie_id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
