# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0013_auto_20170501_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(max_length=11),
        ),
    ]
