# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0014_auto_20170502_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
