# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0017_auto_20170502_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingdata',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='ratingdata',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ratingdata',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
