# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0019_movie_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='links',
            new_name='link',
        ),
    ]
