# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0020_auto_20170502_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['average_rating'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
