# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0024_auto_20170507_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URLDispatcher.RatingUser'),
        ),
    ]
