# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0025_auto_20170507_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='ratingUser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='URLDispatcher.RatingUser'),
            preserve_default=False,
        ),
    ]
