# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLDispatcher', '0027_auto_20170507_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='ratingUser',
        ),
    ]
